function onCreate()
	addHaxeLibrary("FlxG", 'flixel')
	addHaxeLibrary("FlxBar", "flixel.ui")
	addHaxeLibrary("FlxTween", 'flixel.tweens')
	addHaxeLibrary("FlxEase", 'flixel.tweens')
	addHaxeLibrary("AttachedSprite")
	addHaxeLibrary("Std")
	addHaxeLibrary("Paths")
	addHaxeLibrary("lime")
	addHaxeLibrary("Application", "lime.app")
end