function onCreate()
	makeLuaSprite("robloxMenuItems", "content/RobloxMenuItems", 0, 0)
	setObjectCamera("robloxMenuItems", 'other')
	screenCenter("robloxMenuItems", 'xy')
	--addLuaSprite("robloxMenuItems", false)

	makeLuaSprite("robloxBlackBar", "content/blackBar", 0, 0)
	setObjectCamera("robloxBlackBar", 'HUD')
	screenCenter("robloxBlackBar", 'xy')
	addLuaSprite("robloxBlackBar", false)

	makeLuaText("robloxBlackBarTxt", "", 0, 0, getProperty("robloxBlackBar.y") + 14)
	setTextAlignment("robloxBlackBarTxt", 'center')
	setObjectCamera("robloxBlackBarTxt", 'HUD')
	setTextSize("robloxBlackBarTxt", 18)
	updateHitbox("robloxBlackBarTxt")
	screenCenter("robloxBlackBarTxt", 'x')
	addLuaText("robloxBlackBarTxt")
end
function onCreatePost()
	makeLuaSprite("coloredlogo", "content/ui/topBar/coloredlogo", 15, 14)
	setObjectCamera("coloredlogo", 'other')
	addLuaSprite("coloredlogo")
	createButtonBG("coloredlogo")
	makeLuaSprite("chatOff", "content/ui/topBar/chatOff", 55, 15)
	setObjectCamera("chatOff", 'other')
	setProperty("chatOff.offset.x", -3)
	setProperty("chatOff.offset.y", -1)
	addLuaSprite("chatOff")
	createButtonBG("chatOff")
	makeLuaSprite("moreOff", "content/ui/topBar/moreOff", screenWidth - 45, 15)
	setObjectCamera("moreOff", 'other')
	addLuaSprite("moreOff")
	createButtonBG("moreOff")
end

function createButtonBG(name)
	makeLuaSprite(name.."BG", "content/ui/topBar/iconBase", getProperty(name..".x")-4, getProperty(name..".y")-4)
	setObjectCamera(name.."BG", 'other')
	addLuaSprite(name.."BG")
	setObjectOrder(name.."BG", getObjectOrder(name) - 1)
end